name: pythonlibproCI

on:[push]
jobs:
  build:
   runs-on: ubuntu-latest

   steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10
      - name: Install dependencies
        run: pip install -q -r requirements-dev.txt

      - name: flake8
        run: flake8
      - name: test
        run:pytest libpythonpro --cov=libpythonpro
      - uses: codecov/codecov-actions@v2









