name: pythonlibproCI
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "2" ]
  pull_request:
    branches: [ "2" ]

jobs:
  build:
   runs-on: ubuntu-latest

   steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7.4
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.4
      - name: Install dependencies
        run: pip install -q -r requirements-dev.txt

      - name: Lint with flake8
        run: |
            # stop the build if there are Python syntax errors or undefined names
            flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
            # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
            flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
  







