name: pythonlibproCI
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ ]
  pull_request:
    branches: [ ]

jobs:
  build:
   runs-on: ubuntu-latest

   steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.12
      - name: Install dependencies
        run: pip install -q -r requirements-dev.txt
             python3 pip install --upgrade pip
             pipenv install pytest-cov
             pipenv install codecov
             pipenv sync -d
             pipenv install --deploy --dev

      - name: Test with pytest
        run:
            pipenv run pytest libpythonpro --cov=lippythonpro|
            # stop the build if there are Python syntax errors or undefined names
            flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
            # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
            flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Posting Coverage
        env:
         CODECOV_TOKEM:
           run:
             codecov









